baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "custom"

[params]
	sections = [
		{ type = "proposal", title = "Test proposal", description = "Generic proposal", source = "Book ref" },
		{ type = "about", title = "About the project", description = "Lorem ipsum bla blas", keywords = ["A", "B", "C"] },
		{ type = "team", people = [
			{ name = "Jakub Kuzilek", position = "junior researcher", avatar = "images/jakub_kuzilek_avatar.png" },
 			{ name = "Jonas Vaclavek", position = "junior researcher", avatar = "images/jonas_vaclavek_avatar.jpeg" },
			{ name = "Viktor Fuglik", position = "junior researcher", avatar = "images/viktor_fuglik_avatar.jpg" }
		] },
		{ type = "publications", entries = [
			{author = "Jakub Kuzilek", email = "jakub.kuzilek@cvut.cz", ref = "link1"},
			{author = "Jonas Vaclavek", email = "jonas.vaclavek@cvut.cz", ref = "link2"}
		] },
		{ type = "contact_info", email = "jakub.kuzilek@cvut.cz", phone = "1231234234", location = "Prague", schedule ="always open", coordinates = [10, 50]},
		#{ type = "proposal", title = "Another proposal", description = "Unexpected proposal", source = "Another book ref" },
		#{ type = "about", title = "About other projects", description = "asdasdashdbiuasbdoasjndoajsnbdoausnd", keywords = ["steel","ball","race"] }
		
	]
	
	googleMapsAPIKey="AIzaSyDfy5EhePKV9pvK4Lvo-AMdOu83TjaKlnU"
